#Phase 1
FROM node:24 AS build-stage

WORKDIR /usr/src/app

COPY . .

RUN npm ci

ENV VITE_BACKEND_URL=http://localhost:3000

RUN npm run build

#Phase 2
FROM nginx:1.29-alpine

# COPY the directory dist from the build-stage to /usr/share/nginx/html
COPY --from=build-stage /usr/src/app/dist /usr/share/nginx/html